version: '3.2'
services:
  db:
    environment:
      - POSTGRES_USER=postgres-dev
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=postgres-dev
  app:
    environment:
      RAILS_ENV: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
