version: '3.2'
services:
  db:
    environment:
      - POSTGRES_USER=postgres-prod
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=postgres-prod
  app:
    environment:
      RAILS_ENV: production
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "4000:3000"
